# Generated by Django 2.2 on 2019-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lastmname',
            new_name='lastname',
        ),
    ]
